#~~~~~~~~~~~~~~~~~ Variables ~~~~~~~~~~~~~~~~~~~#

NAME		=	libftprintf.a

HEADER		=	headers

LIBFT		=	libft

SRCS_DIR	=	src/

OBJS_DIR	=	obj/

COMP		=	gcc

COMPFLAGS	=	-Wextra	-Werror	-Wall -I

AR			=	ar rcs

RM			=	rm -rf

#~~~~~~~~~~~~~~~ Source Files ~~~~~~~~~~~~~~~~~#

SRCS		=	$(addprefix $(SRCS_DIR), $(addsuffix .c, $(SRCS_FILES)))
OBJS		=	$(addprefix $(OBJS_DIR), $(addsuffix .o, $(SRCS_FILES)))

#~~~~~~~~~~~~~~~~~ Recipes ~~~~~~~~~~~~~~~~~~~#

